# https://github.com/P3TERX/Gitpod-OpenWrt
# OpenWrt build environment in Gitpod
# MIT License
# Copyright (c) 2020 P3TERX <https://p3terx.com>

name: Docker images publish

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    paths:
      - 'Dockerfile'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and push
      uses: docker/build-push-action@v1
      with:
        push: true
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: p3terx/gitpod-openwrt
        tags: latest
        dockerfile: Dockerfile
        path: .
